#spring:
#  datasource:
#    url: jdbc:mysql://localhost/users-posts
#    username: root
#    password: rootpassword
#    driver-class-name: com.mysql.jdbc.Driver
#
#    jpa:
#      hibernate:
#        ddl-auto: create
